<?php echo $this->doctype('HTML5')?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <?php echo $this->headMeta()
    ->appendName('keywords', $this->translate("keywords"))
    ->appendName('description', $this->translate("description")) ?>

  <?php echo $this->headTitle($this->document->title)
    ->headTitle($this->translate("title"))->setSeparator(' - '); ?>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="shortcut icon" href="/<?php echo $this->baseUrl()?>website/public/favicon.ico" />
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="/<?php echo $this->baseUrl()?>website/public/css/style.css" />
  <link rel="stylesheet" type="text/css" href="/<?php echo $this->baseUrl()?>website/public/css/style-responsive.css" />
  <link rel="icon" href="/<?php echo $this->baseUrl()?>website/public/img/favicon.ico" type="image/x-icon" />
</head>

<body>

<header id="home">
  <div class="container language-container">
    <ul class="language-switch pull-right">
      <li><a href="/pl"><img src="/<?php echo $this->baseUrl()?>website/public/img/pl-flag.png" alt="polski" title="polski" /></a></li>
      <li><a href="/en"><img src="/<?php echo $this->baseUrl()?>website/public/img/en-flag.png" alt="english" title="english" /></a></li>
      <!--<li><a href="/de"><img src="/<?php echo $this->baseUrl()?>website/public/img/de-flag.png" alt="deutsch" title="deutsch" /></a></li>
      <li><a href="/fr"><img src="/<?php echo $this->baseUrl()?>website/public/img/fr-flag.png" alt="français" title="français" /></a></li>
      <li><a href="/es"><img src="/<?php echo $this->baseUrl()?>website/public/img/es-flag.png" alt="español" title="español" /></a></li>
      -->
    </ul>
  </div>

  <?php echo $this->render('shared/_parallax.phtml')?>

  <?php echo $this->render('shared/_nav.phtml')?>

  <div class="container">
    <div class="row">

    </div> 
  </div> 
</header>
