<nav id="navbar" class="navbar navbar-static sticky-navigation">
  <div class="navbar-inner">
    <div class="container">
      <img class="pull-left nav-logo" src="/<?php echo $this->baseUrl()?>website/public/img/domi-net_white.png" alt="Domi-Net Dominik Zborowski">
      <img class="pull-left nav-logo-small" src="/<?php echo $this->baseUrl()?>website/public/img/domi-net_white_small.png" alt="Domi-Net Dominik Zborowski">
      <ul id="top-menu" class="nav navbar-nav pull-right">
        <li class="active"><a href="#home"><?php echo $this->input('home', array("width" => 100))?></a></li>
        <li class=""><a href="#about"><?php echo $this->input('about', array("width" => 100))?></a></li>
        <li class=""><a href="#contact"><?php echo $this->input('contact', array("width" => 100))?></a></li>
      </ul>
    </div>
  </div>
</nav>
