<section id="intro">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <img alt="Domi-Net Dominik Zborowski" src="/<?php echo $this->baseUrl()?>website/public/img/domi-net_logo.png" />
        <h5 class="text-muted"><?php echo $this->input('motto', array("width" => 540))?></h5>
      </div>
    </div>
  </div>
</section>

<section id="about" class="gray">
  <div class="container">
    <div class="row margined">
      <div class="col-lg-12">
        <div class="row-fluid">
          <div class="col-lg-5">
            <h2><?php echo $this->input('about_title', array("width" => 300))?></h2>
            <p>
              <?php echo $this->wysiwyg("about_content", array(
                "width" => 300,
                "height" => 300));
              ?>
            </p>
            <blockquote>
              <p><?php echo $this->textarea('quote', array("width" => 300, "height" => 100))?></p>
              <small><?php echo $this->input('quote_author', array("width" => 300))?></small>
            </blockquote>
          </div>
          <div class="col-lg-6 col-offset-1">
            <div class="text-center margined">
              <?php echo $this->image("preview", array(
                "width" => 600,
                "id" => 'preview',
                "highResolution" => 2
              )); ?>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="contact">
  <div class="container">
    <div class="row margined">
      <div class="col-lg-12">
        <div class="row-fluid">
          <div class="col-lg-6" id="map">

          </div>
          <div class="col-lg-6 text-right">
            <h2><?php echo $this->input('contact_title', array("width" => 300))?></h2>

            <address>
              <?php echo $this->wysiwyg("contact_content", array(
                "width" => 300,
                "height" => 300));
              ?>
            </address>
            <?php
            $link = $this->link("facebook_link");
            $image = $this->image("facebook_image", array(
              "title" => "",
              "width" => 150,
              "height" => 48,
              "thumbnail" => array(
                "width" => 150,
                "height" => 48
              ),
              "highResolution" => 2
            ));
            ?>

            <?php if ($this->editmode) { ?>
                <?php echo $this->link("facebook_link"); ?>
                <?php echo $this->image("facebook_image"); ?>
            <?php } else { ?>
                <a title="<?php echo $link->getTitle()?>" class="" target="<?php echo $link->getTarget()?>" href="<?php echo $link->getHref()?>"><?php echo $image; ?></a>
            <?php } ?>
          </div>
        </div>
        
      </div>
    </div>
  </div>
</section>



